# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 02:11
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='empty content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lnglat',
            field=models.CharField(blank=True, max_length=50, validators=[blog.models.lnglat_validator]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='포스팅 제목으로 노출됩니다. 최대 100자까지 지원됩니다.', max_length=100, verbose_name='제목'),
        ),
    ]
